#!/usr/bin/env python3
"""
Read raw/peing_qa_traditional.json and write chapters/1-quotes.tex.

Each question–answer pair becomes one numbered \\chapter (question in the TOC
and heading) followed by the answer. id, url, and timestamps are omitted.

Regenerate:
  python3 convert_peing_qa_to_latex.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def escape_latex(text: str) -> str:
    """Escape characters that break LaTeX when pasted verbatim."""
    if not text:
        return ""
    replacements = (
        ("\\", r"\textbackslash{}"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("^", r"\textasciicircum{}"),
        ("_", r"\_"),
        ("~", r"\textasciitilde{}"),
    )
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def text_to_latex_body(text: str) -> str:
    """Turn plain text (possibly multi-paragraph) into LaTeX body fragments."""
    paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
    if not paragraphs:
        return ""
    return "\n\n".join(escape_latex(p) for p in paragraphs)


def flatten_question(question: str) -> str:
    """Single-line question for the TOC."""
    return " ".join(question.split())


def format_question_heading(question: str) -> str:
    """Multi-line question for the chapter heading on the page."""
    lines = [line.strip() for line in question.split("\n") if line.strip()]
    if not lines:
        return ""
    if len(lines) == 1:
        return escape_latex(lines[0])
    return r" \\[0.35em] ".join(escape_latex(line) for line in lines)


def load_pairs(path: Path) -> list[tuple[str, str]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    items = list(data.values())
    items.sort(key=lambda item: item.get("answer_created_at", ""))
    pairs: list[tuple[str, str]] = []
    for item in items:
        question = item.get("question", "").strip()
        answer = item.get("answer", "").strip()
        if not question and not answer:
            continue
        pairs.append((question, answer))
    return pairs


def emit_chapter(pairs: list[tuple[str, str]], out: Path) -> None:
    header = r"""% Auto-generated by convert_peing_qa_to_latex.py — do not edit by hand.
% Regenerate: python3 convert_peing_qa_to_latex.py

\chapter*{問答語錄}
\addcontentsline{toc}{chapter}{問答語錄}

"""
    blocks: list[str] = [header]
    for question, answer in pairs:
        toc = escape_latex(flatten_question(question))
        heading = format_question_heading(question)
        body = text_to_latex_body(answer)
        blocks.append(
            f"\\chapter[{toc}]{{{heading}}}\n"
            f"\\qaanswer{{\n{body}\n}}\n\n"
        )
    out.write_text("".join(blocks).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    root = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description="Generate chapters/1-quotes.tex from Peing Q&A JSON.")
    ap.add_argument(
        "--json",
        type=Path,
        default=root / "raw" / "peing_qa_traditional.json",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=root / "chapters" / "1-quotes.tex",
    )
    args = ap.parse_args()
    pairs = load_pairs(args.json)
    emit_chapter(pairs, args.out)
    print(f"Wrote {len(pairs)} Q&A pairs to {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
